### ISSUE TITLE
Doesn't have the same behavior as css property 'background-size: cover;'

### ISSUE THREAD

**Issue by lateek35** [agilie/canvas-image-cover-position#1]
Find an issue with the script [there](https://github.com/agilie/canvas-image-cover-position/blob/master/index.js#L25), causing wrong calculation.
I think it should rather compare container's ratio with image's ratio.

Issue exemple: 
https://jsfiddle.net/02h96z4p/1/

**Comment by fargo23** [comment]
> Find an issue with the script [there](https://github.com/agilie/canvas-image-cover-position/blob/master/index.js#L25), causing wrong calculation.
> I think it should rather compare container's ratio with image's ratio.
> 
> Issue exemple:
> https://jsfiddle.net/02h96z4p/1/

Yes, you are absolutely right, I redid the functionality.
Fixed in version 1.1.0
